name: daily_cats
description: A minimal app that shows you a cute cat every day ðŸ±
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.0
  android_alarm_manager_plus: ^4.0.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_gallery_saver_plus: ^4.0.1
  connectivity_plus: ^5.0.1
  permission_handler: ^11.3.1
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  page_view_indicators: ^2.0.0
  flutter_launcher_icons: ^0.13.1   # latest

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png 